<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DailyTipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dailyTips = [
//            SA seeder
            ['code' => 'SA', 'title' => 'Start Your Day with Reflection', 'description' => `This morning, tap into your natural ability to see the big picture by beginning your day with a period of quiet contemplation. Set aside 15–20 minutes and take a look at all of the pieces of your day. Notice any potential challenges and notice the pathways to create solutions to benefit all.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Delegate Tasks', 'description' => `Today, pay close attention to opportunities for delegating tasks in all areas of your life by identifying tasks that can be assigned to others, empowering team or family members by providing clear instructions and support, allowing you to concentrate on your strengths while empowering others.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Activate Leadership in Various Aspects', 'description' => `As a natural leader, spend time today seeing where you can activate leadership activities in various aspects of your life. Consider volunteering to lead a community project or charity event, mentoring a younger colleague or student, or overseeing a family gathering, remembering that leadership isn't confined to the workplace.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Harness Your Panoramic Perspective', 'description' => `To harness your panoramic perspective, set aside time today to find solutions to challenges in your life.  Here are some suggestions:  Facilitate a brainstorming session with your team or family, create a mind map to visualize problems and their interconnections, or simply look at issues from multiple angles before making decisions. Use your ability to see the whole picture to develop comprehensive solutions that benefit everyone involved.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Embrace Your Benevolent Nature', 'description' => `Today, embrace your benevolent nature by finding ways to contribute to the well-being of others and your community, such as dedicating time to support others in seeing the big picture of what they may be experiencing, helping colleagues or friends find solutions, and practicing random acts of kindness throughout your day.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Focus on Big-Picture Activities', 'description' => `To optimize your day, focus on activities that allow you to take a big-picture approach by envisioning all the pieces of your day, your personal goals, family objectives, and any work or community projects in which you are involved, utilizing your ability to see all components of a situation as a valuable asset in any planning process.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Clarify Your Pondering Nature', 'description' => `As someone who commands respect, be aware today that others might misinterpret your pondering nature; if you notice people perceiving you as aloof or indecisive, take a moment to explain that you're considering all pieces of the puzzle to see where they fit in the bigger picture, preventing misunderstandings.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Practice Active Listening', 'description' => `To embody your best self today, practice active listening in all your interactions by giving your full attention to others, acknowledging their perspectives, and demonstrating that you value their input, reinforcing your diplomatic nature and helping prevent misunderstandings.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Apply Solutions Benefiting the Whole', 'description' => `Recognize your natural ability to see solutions that benefit the whole; when faced with any challenges today, consciously apply your panoramic perspective by considering how your solution might affect all involved parties, proposing ideas that create win-win situations, and sharing your solutions by highlighting benefits for everyone.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Promptly Address Issues', 'description' => `Given your need for respect, it's important today (and every day) to communicate your expectations clearly and respectfully, addressing any perceived disrespect promptly and diplomatically, and recognizing and appreciating when others show you respect.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Delegate Effectively', 'description' => `To optimize your day, focus on delegating tasks effectively by identifying tasks that can be delegated to others, empowering team members or family members by assigning them responsibilities, and providing clear instructions and support for delegated tasks, allowing you to concentrate on developing high-level solutions.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Maintain Natural Authority', 'description' => `As someone who commands respect, be aware today of how you present yourself and interact with others to maintain your natural authority by practicing maintaining a confident and open posture, speaking clearly and thoughtfully with moments of reflection, and genuine interest in others' perspectives and ideas.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Balance Leadership with Listening', 'description' => `To embody your best self today, balance your leadership responsibilities with moments of actively listening to others by taking time to listen without immediately offering solutions, showing appreciation for the efforts and contributions of those around you, and practicing patience when others need time to process information or make decisions.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Make a Positive Impact', 'description' => `Today, recognize your strength in seeing solutions that benefit the greater good and use this ability to make a positive impact by considering how solutions affect all parties, proposing win-win ideas, and sharing your solutions by highlighting benefits for everyone.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Seek Leadership Opportunities', 'description' => `As a natural leader, explore opportunities today to lead and guide others in various aspects of life such as volunteering for a community project or charity event, offering to mentor a younger colleague or student, or overseeing a family gathering.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Practice Presence', 'description' => `Throughout the day, practice being fully present in each moment, whether during meetings, conversations, or personal activities, allowing you to make more thoughtful decisions and respond effectively to situations.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Embrace Your Benevolent Nature', 'description' => `Today, embrace your benevolent nature by finding ways to contribute to the well-being of others by dedicating time to support them in seeing the big picture of their experiences, helping colleagues or friends find solutions, and practicing random acts of kindness throughout your day.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SA', 'title' => 'Discovering Solutions to Benefit the Whole', 'description' => `Throughout the day, engage in activities that allow you to see all the pieces of a situation and find solutions that benefit the whole by facilitating brainstorming sessions, creating mind maps to visualize solutions and their interconnections, and practicing looking at issues from multiple angles before making decisions.`, 'created_at' => now(), 'updated_at' => now()],
//            MA seeder
            ['code' => 'MA', 'title' => 'Channel Your Energy Productively', 'description' => 'Today, harness your energetic nature by channeling your passion into productive activities that allow you to get things done, allowing your natural enthusiasm to initiate momentum.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Cultivate Patience', 'description' => 'Today, practice patience by counting to ten when feeling frustrated, allowing yourself a moment to breathe before reacting, which can temper your abruptness and improve interactions with others.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Manage Your Direct Approach', 'description' => 'Your direct approach is an asset in your life as it allows you to tackle things head on.  Today, pay attention to how your actions and words affect those around you.  At times, others may misunderstand the abrupt manner in which you respond or interact.  Communicate your need to take a direct route between A and B', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Temper Your Natural Intensity', 'description' => '<h1>Remember the Energetic Aspect of Your Nature</h1>
        <p>
            Your energetic nature has a directness that can be both a strength and a potential source of misunderstanding for others. Today (and every day), consider tempering your natural intensity by following these practices:
        </p>
        <ul>
            <li>Count to ten when feeling frustrated and before reacting</li>
            <li>Practice deep breathing exercises throughout the day</li>
            <li>Practice active listening in conversations</li>
            <li>Count to three before responding in discussions</li>
        </ul>', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Embrace Your Warrior Spirit', 'description' => '<h1>Guidance for Your Energetic Trait</h1>
        <p>
            The innate tendency of your Energetic trait is to “right the wrong” in a situation. When confronting challenges today (or any day), remember to temper your input with diplomacy. Your courage in facing issues head-on is admirable, but a tactful approach can lead to better outcomes.
        </p>
        <ul>
            <li>Before addressing an issue, write down your thoughts</li>
            <li>Ask for input before making major decisions</li>
            <li>Seek a mediator for potentially contentious discussions</li>
        </ul>', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Maximize your Energetic Trait', 'description' => 'Focus on effective time management today. Implement a time-blocking technique to remain energy efficient around the work you want to get done (e.g. work for 90-minute time blocks, then take a 15 minute break, or work for 40-minutes, then take a 5 minute break). Structuring your day this way can help you access your energy most productively', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Your Words Carry Weight', 'description' => 'Pay close attention to the power of your words today. Because your Energetic trait is direct, today, practice adjusting your responses to be in alignment with your innate desire to honor others.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Let Your Integrity Be Your Guide', 'description' => 'Your commitment to truth and justice can set a powerful example for those around you. Take a moment today and remember the last time you stood up for what’s right. As you move forward in life, remind yourself to always let your integrity lead the way rather than allowing any anger that might be sparked to lead the way in making choices.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Explain Your Directness', 'description' => 'Because your Energetic trait is straightforward, today, explain to others this direct aspect of your nature. It can help them understand you better and eliminate misunderstandings around your abruptness', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Add a Friendly Comment', 'description' => 'Your Energetic trait gets straight to the point, today, practice adding a friendly comment before discussing business.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'The Optimal Way to “Fix”', 'description' => `Your Energetic trait makes you good at fixing problems…and you are direct. Today, practice addressing issues in a way that doesn't upset others.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MA', 'title' => 'Managing the “Crisis”', 'description' => 'Your Energetic nature makes you great in a crisis. If a problem comes up today, take a deep breath and tackle it head-on.', 'created_at' => now(), 'updated_at' => now()],

//            JO seeder

            ['code' => 'JO', 'title' => 'Connect with Others', 'description' => 'Today, harness your Absorptive trait by scheduling time to connect with a family member, friend, or colleague who might benefit from your empathetic support, offering a comforting presence that others find reassuring.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Solve a Small Problem', 'description' => 'As a natural solutionist, challenge yourself today to solve a small problem at home, in your community, or in your workplace, using your common-sense wisdom to make a significant impact on those around you.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Dedicate Time to Learning', 'description' => 'Today, set aside dedicated time to learn something new, feeding your natural curiosity and expanding your vast knowledge base, which you can effortlessly draw upon in the future.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Spread Joy', 'description' => 'With your cheerful disposition, spread joy today by sharing a positive story or compliment with at least three people, brightening their day and reinforcing your engaging nature.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Initiate Collaboration', 'description' => 'Today, initiate a group activity or discussion at work or in your social circle, engaging your gregarious side and fostering team spirit through your collaborative nature.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Practice Letting Go', 'description' => 'Because you have a tendency to hold onto things, design a "let go" ritual today by identifying one small resentment or worry and consciously releasing it, promoting greater harmony within.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Share Your Generosity', 'description' => `Today, channel your generous spirit by sharing kindness, whether it's offering advice, resources, or simply giving your time to someone in need, embodying your natural generosity.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Frame Your Insights Thoughtfully', 'description' => 'When sharing with others today, practice framing your wisdom as personal experiences rather than absolute truths by using phrases like "In my experience..." to make your insights more relatable.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Ask Thoughtful Questions', 'description' => 'As a natural empath, channel your desire to help today by asking thoughtful questions, allowing others to discover solutions themselves while still benefiting from your wisdom.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Encourage Shared Learning', 'description' => 'Today, instead of correcting others directly, suggest looking up information together, fostering a shared learning experience and nurturing your collaborative spirit.', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Gauge Appropriateness', 'description' => `Use your empathetic nature today to sense when it's appropriate to share your knowledge and when it's better to hold back, ensuring your contributions are well-received.`, 'created_at' => now(), 'updated_at' => now()],

            ['code' => 'JO', 'title' => 'Create Open Dialogue', 'description' => `Today, use your engaging nature to create an open dialogue where knowledge sharing feels like a mutual exchange, enhancing connections and avoiding the impression of lecturing.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Prioritize Your Well-being', 'description' => `Remember that true empathy requires stability; today, prioritize your own well-being before deeply engaging with others' pain, ensuring you're grounded when offering support.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Engage in Storytelling', 'description' => `Today, share a personal story that imparts wisdom or joy, leveraging your natural storytelling ability to connect with others and share valuable insights.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Celebrate Your Joyful Nature', 'description' => `Throughout the day, embrace and share your joyful disposition by engaging in activities that make you happy, spreading positivity to those around you.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Offer a Helping Hand', 'description' => `Today, look for opportunities to offer assistance to someone in need, reflecting your compassionate and generous nature in practical ways.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Practice Becoming Aware of How You Eat', 'description' => `Today, honor your body's needs by choosing nourishing foods that support your well-being and reflect your natural harmony with life.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Share Your Knowledge', 'description' => `Use your vast "library of understanding" today to help someone solve a problem, offering your insights in a supportive and collaborative manner.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JO', 'title' => 'Collaborate on a Project', 'description' => `Today, collaborate with others on a project or idea, valuing the shared experience and collective wisdom that comes from teamwork.`, 'created_at' => now(), 'updated_at' => now()],

//            LU seeder
            ['code' => 'LU', 'title' => 'Set Aside Alone Time', 'description' => `Because an aspect in your nature is reclusive, set aside dedicated "alone time" today to connect with your solitary aspect. Create a cozy, private space where you can retreat without interruptions, ensuring you have regular opportunities to recharge.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Personalize Your Surroundings', 'description' => `Your Romantic trait has you naturally desiring an intimate rapport with your surroundings. Today, personalize your workspace…consider the objects you have in your space and make sure they are meaningful, consider the lighting, and any other factors that allow you to create a comfortable environment that resonates with your reclusive nature.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Connect with Water', 'description' => `You are naturally drawn to water as experiencing its flow is harmonizing for you. If possible, spend time near a body of water today—whether it's the ocean, a lake, or a stream. If that's not feasible, listen to recordings of water sounds or consider adding a small fountain to your space to incorporate the water element into your daily routine.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Communicate Your Need for Focus', 'description' => `Because the more reclusive side to your nature works best on your own with no interruptions, communicate your need for uninterrupted work time to colleagues and family members. Use "do not disturb" signs or signals to indicate when you're in deep focus mode, allowing you to be more productive.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Practice Assertiveness', 'description' => `The non-confrontational aspect of your nature can sometimes lead to sacrificing your wants and needs. Today, practice expressing your needs and boundaries in a gentle but clear manner, ensuring your voice is heard without causing discomfort.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Cultivate Thankfulness', 'description' => `Because an aspect of your nature has a tendency towards nostalgia and can feel melancholy at times, write down three things for which you are thankful today. Continue to add to this list, and revisit it whenever you need a gentle reminder.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Create a Daily Ritual', 'description' => `As your Romantic trait has you thriving in quiet and secure environments, create a daily ritual that allows you to immerse yourself in serenity. You might dim the lights, play soft music, or engage in calming activities to nurture your inner peace.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Engage in Solo Creativity', 'description' => `Because your creativity often manifests in isolation, dedicate time today to work on a solo creative project. Whether it's writing, painting, or crafting, allow yourself to explore your artistic side without external pressures.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Schedule Solitude', 'description' => `Create designated alone time in your daily schedule today by setting specific periods for solitude. Treat these moments as important appointments with yourself to ensure you have regular opportunities to retreat.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Avoid Confrontations', 'description' => `If possible, steer clear of confrontational situations today, aligning with your non-confrontational aspect of your nature and preserving your peace.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Opt for Low-Intensity Social Interactions', 'description' => `Seek out low-intensity social interactions today by choosing one-on-one meetings or small group gatherings. This helps you connect with the more solitary aspect of your nature - still maintaining connections without overwhelming your need for quiet.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Embrace Your Reclusive Nature', 'description' => `Accept and embrace your reclusive nature today, recognizing that your need for solitude is a strength that allows you to recharge and be your best self.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Limit Obligations', 'description' => `Today, consider saying no to non-essential obligations, giving yourself permission to prioritize the aspect of your nature that has an innate need for solitude.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Limit Exposure to Crowded Spaces', 'description' => `Because the more reclusive side of your nature does not do well in crowded spaces, plan your day to avoid them when possible, choosing quieter environments that make you feel comfortable.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LU', 'title' => 'Enjoy Silence', 'description' => `Embrace moments of silence throughout your day, allowing yourself to recharge without any external noise or distractions.`, 'created_at' => now(), 'updated_at' => now()],


            //            VUN seeder

            ['code' => 'VEN', 'title' => 'Ease Into Your Day', 'description' => `This morning, allow yourself extra time to ease into your day, honoring your relaxed and laid-back nature by avoiding rushing and starting your tasks calmly.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Schedule a Power Nap', 'description' => `Since you benefit from a brief respite, ensure you have a 20 to 30-minute nap scheduled today between 2 and 5 PM to recharge and maintain your energy levels.  Notice after you take your nap how rejuvenated you are.  Not everyone benefits from this afternoon respite.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Acknowledge Procrastination Positively', 'description' => `Today, recognize that your tendency to procrastinate at times is simply a reflection of your relaxed nature; use this time to see what is most useful in the moment rather than beating yourself up or putting added pressure on yourself.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Set Gentle Reminders', 'description' => `Today, use gentle reminders like setting alarms or calendar notifications to help manage tasks and appointments without adding stress to your laid-back approach.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Be the Calm in the Storm', 'description' => `Throughout the day, notice opportunities where you can be the "calm in the storm" for others, using your warm and charming nature to ease tensions.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Engage in Healing Activities', 'description' => `Since your Sympathetic trait makes you a natural-born healer (by others simply being in your presence), engage in activities today that promote healing, such as comforting a friend in need or listening to someone share a challenge. If you are officially engaged in the healing arts, notice when you are working with a client how your calming presence impacts the healing experience.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Reflect on Your Positive Impact', 'description' => `This evening, reflect on the positive impact the nurturing and relaxed aspect of your nature has on those around you, acknowledging the value you bring to others' lives.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Embrace Your Nurturing Nature', 'description' => `Because you are a natural nurturer, start your day today by checking in with loved ones or colleagues to offer support and encouragement.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Optimize Your Relationship With Time', 'description' => `Because you have a prominent Sympathetic trait, punctuality might not always be your strong suit. Today, communicate your relaxed approach to time with others to set realistic expectations.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEN', 'title' => 'Transition Without Stress', 'description' => `Your Sympathetic trait provides you with a relaxed, laidback nature. Allow yourself extra time in the morning to “ease into your day” and to transition between tasks without stress.`, 'created_at' => now(), 'updated_at' => now()],

            //            MER seeder
            ['code' => 'MER', 'title' => 'Practice Active Listening', 'description' => `Today, during conversations, practice active listening to ensure your quick responses are well-informed and considerate of others' perspectives, enhancing your connection with them.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Strategize Your Tasks', 'description' => `Today, use the aspect of your nature that is naturally skilled at strategic thinking to outline your most critical tasks and allocate time for each, helping you fine-tune your focus and energy on what truly matters`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Offer Problem-Solving Support', 'description' => `Today, offer your natural problem-solving abilities to support others in any challenging situations that might arise. This will strengthen bonds and showcase your quick ability to highlight the problem so solutions can be found. `, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Engage in Mind-Challenging Activities', 'description' => `Since an aspect of you is a critical thinker by nature, engage in an activity today that challenges your mind, such as puzzles or a quick strategic game, keeping your analytical skills sharp.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Set Boundaries on Information Sharing', 'description' => `Given that your Perceptive trait tends to be more covert by nature, set boundaries today on what information you choose to withhold, consider sharing more of the necessary details. This will foster trust with others.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Practice Transparency', 'description' => `Today, practice a bit of transparency when appropriate; sharing information openly can build trust and prevent misunderstandings with others.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Satisfy Your Curiosity', 'description' => `Being naturally curious, dedicate time today to explore a new topic…this will satisfy your curiosity and keep your mind engaged.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Schedule Uninterrupted Work Time', 'description' => `Your Perceptive trait provides you with the natural ability to maintain a high level of concentration. Today (and moving forward), schedule daily uninterrupted time blocks for deep work. Use this time to tackle complex problems requiring your full attention.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Help Others with Troubleshooting', 'description' => `As a natural trouble-shooter, use your problem-solving skills today to help others, strengthening relationships and showcasing your valuable perceptions.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Review Your Work for Details', 'description' => `Your Perceptive trait makes you detail-oriented; review each piece of work you create today to catch any overlooked details, enhancing the quality of your output.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Reflect on Territorial Tendencies', 'description' => `Since your Perceptive trait can cause you to experience territorial feelings at times, today, reflect on those times in the past when you’ve had possessive feelings or interactions around certain people, places and things in your life. Set an intention for yourself moving forward to practice being open to allowing experiences to unfold naturally, without needing a certain outcome. The freedom that exists in this space cultivates trust and openness.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Manage Impatience', 'description' => `Today, be mindful of your quick processing speed that can lead to impatience; practice patience by giving others time to express themselves fully.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MER', 'title' => 'Communicate Constructively', 'description' => `Because your Perceptive trait makes you a critical thinker, remind yourself that others can, at times, receive your feedback as criticism. Today, focus on communicating your perceptions constructively, framing them in a way that is helpful and encouraging.`, 'created_at' => now(), 'updated_at' => now()],

            //            SO seeder
            ['code' => 'SO', 'title' => 'Engage in Creative Exploration', 'description' => `Today, leverage your ability to access possibility-filled solutions by engaging with others to explore creative ideas and resolve any challenges.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Explore an Interest that Excites You', 'description' => `Since the childlike wonder in your Effervescent trait is prominent, dedicate time today to explore a new hobby or interest that excites you, fueling your curiosity and fun-loving nature.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Spread Kindness with a Smile', 'description' => `With your naturally delightful disposition, remember to smile and greet everyone you meet today, spreading kindness and uplifting the spirits of those around you.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Enhance Focus with Time Blocks', 'description' => `To maintain productivity despite potential distractions, use a timer today to focus on one task at a time in dedicated intervals, helping you harness your Effervescent energy effectively.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Capture Your Thoughts', 'description' => `Because your Effervescent trait processes information quickly, remember to capture your thoughts today by jotting them down on paper or using a digital tool to retain your brilliant ideas`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Incorporate Playfulness into Your Day', 'description' => `As you are playful by nature, take breaks today to engage in fun activities like games or light-hearted exercises, allowing you to refresh and embrace your Effervescent side.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Communicate Fleeting Thoughts Respectfully', 'description' => `Today, if you find yourself announcing fleeting thoughts, practice being sensitive to others by explaining that you're sharing to capture the idea, helping prevent misunderstandings.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Make Time for Fun', 'description' => `Having fun is a natural part of your nature; ensure you find time today to "play" in ways that inspire you, keeping your spirits high and creativity flowing.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => `Be Mindful of Others' Perspectives`, 'description' => `Because others may not be as fun-loving, today, consider their perspectives and adjust your interactions accordingly without dimming your brilliant nature.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Set Aside Time for Reflection', 'description' => `Since you process information swiftly, set aside time today to reflect on new information to ensure full understanding and retention.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SO', 'title' => 'Embrace Your Childlike Wonder', 'description' => `Today, allow your childlike wonder to lead you by exploring nature, trying something new, or simply marveling at the world around you`, 'created_at' => now(), 'updated_at' => now()],
//            DE seeder
            ['code' => 'DE', 'title' => 'Embrace Transformative Projects', 'description' => `Today, identify a specific area in your home or workspace that needs improvement, and begin planning how you can transform it to better suit your needs.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Seek Out Opportunities for Change', 'description' => `Actively look for transformational opportunities today, whether in your personal life, community, or workplace, to satisfy your innate drive to initiate change.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Reflect on Past Transformations', 'description' => `Take time today to reflect on past changes you've initiated, considering what worked well and what you learned, to inform future transformative efforts.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Engage in Discussions About Change', 'description' => `Participate in conversations today that stimulate exploration around initiating change, sharing your experiences and ideas to inspire others.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Start a Small Improvement Project', 'description' => `Choose a small project today, like organizing a drawer or updating a digital file system, to engage your drive for initiating change in a manageable way.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Support Others in Transformation', 'description' => `Identify someone who could benefit from change and offer your support today, acting as a catalyst for their transformation process.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Channel Frustration into Action', 'description' => `If you feel frustration building today, redirect that energy into productive action by starting a transformative project or activity.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Recognize Stagnation and Act', 'description' => `Whenever your day feels stagnant, set an intention to recognize your need for change and take steps to initiate it in areas that feel unsatisfying.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Rearrange Your Space', 'description' => `Today, rearrange some furniture or add or remove some decor in your home or office to create a fresh environment, satisfying your innate need for transformation.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Plan a Big Project', 'description' => `Begin planning a larger transformational project today, such as renovating a room or starting a fitness regimen, to engage your drive for significant change`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Adopt a New Technology', 'description' => `Explore or adopt a new technology or tool today that can improve efficiency in your work or personal life, initiating change through innovation.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Improve a Process', 'description' => `Identify an inefficient process at work or home today and develop a plan to improve it, initiating change that benefits everyone involved.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Embrace a Healthy Habit', 'description' => `Because one of your driving forces is about Initiating Change, start a new healthy habit today, such as drinking more water or taking daily walks, transforming your well-being over time.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DE', 'title' => 'Initiate a Workplace Improvement', 'description' => `Because Initiating Change is one of your drivers, propose a change at work today that can enhance productivity or morale, when implemented it will not only give you energy but it will also contribute to transforming the lives of others.`, 'created_at' => now(), 'updated_at' => now()],
//            DOM seeder
            ['code' => 'DOM', 'title' => 'Organize Your Tasks', 'description' => `Because your Creating Order driver thrives on structure, identify the top three tasks for the day and write them down. Allocate specific time slots for each task in your calendar, and review the list at the end of the day to carry over unfinished tasks.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Simplify Your Routines', 'description' => `Your Creating Order driver provides you with the ability to streamline processes. Today, simplify your daily routines to save time by noting any time-wasting activities and eliminating unnecessary steps.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Tidy Up Small Areas Daily', 'description' => `Because you have a drive to Create Order, dedicate at least 10 minutes today (and every day) to tidy up a small area like a desk or a drawer, maintaining a clutter-free environment.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Establish a Weekly Meal Plan', 'description' => `Because you excel at creating systems, establish a weekly meal plan today to reduce daily decision-making stress. Make a shopping list and set an intention to prepare ingredients in advance to save time during the week.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Organize Storage Spaces', 'description' => `Your Creating Order driver provides you with the natural talent to maximize resources. Today, create a plan to organize your storage spaces. Schedule a decluttering session for yourself with the intention to arrange items for easy access.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Implement Time-Blocking', 'description' => `Your Creating Order driver naturally helps you manage time well. Create a time-blocking system today to allocate specific times for specific tasks, enhancing focus and productivity.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Practice Transparency', 'description' => `When your Creating Order driver isn’t able to create order, it can lead to manipulation. Today, practice transparency by openly sharing with others your need to create order and your specific plans and intentions. This builds trust and reduces misunderstandings.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Avoid Manipulation', 'description' => `Recognize that not everyone creates order in the same way you do. Today, avoid using manipulation to get others to align with your orderly needs. Instead, cultivate open communication and appreciate different perspectives.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Delegate Effectively', 'description' => `Your Creating Order driver helps you effectively delegate. Today, list tasks that can be delegated at work or home, identify capable individuals. When you delegate, communicate your expectations related to the task clearly, and schedule a follow up to ensure completion.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Organize Digital Files', 'description' => `Because you are skilled at arranging, carve out time today to begin organizing your digital files and emails. Create folders and subfolders, and set an intention to regularly delete unnecessary files to keep your digital space tidy`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Create Checklists for Organization', 'description' => `Use checklists today to keep track of tasks and ensure nothing is overlooked. When you create your checklists, consider prioritizing and categorizing your lists.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Use a Planning System', 'description' => `Because you have Creating Order as a driver, purchase, create or activate (or refine) a planning system today. Whether it's a hardcover planner, a notebook or a digital app, utilize this to schedule your tasks and appointments, maintaining order in your daily activities.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Develop Standard Procedures', 'description' => `If applicable, create standard operating procedures for routine tasks today, streamlining processes and making them more efficient.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Organize Emails', 'description' => `Because your Creating Order driver needs to organize, today, begin the process of sorting your emails into folders or labels. Consider unsubscribing from unnecessary newsletters or subscriptions, and maintain an organized inbox`, 'created_at' => now(), 'updated_at' => now()],

            ['code' => 'DOM', 'title' => 'Establish Routines', 'description' => `Your Creating Order driver aligns with routines. Today, consider what area of your life can benefit from a routine and establish a new one…perhaps it’s a self-care routine, a new eating plan, or exercise program.  Remember, routines bring consistency and order to your life.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Create a Daily Schedule', 'description' => `If you don’t already have a detailed schedule for your day, today allocate time for work, breaks, and personal activities. If you already have a detailed schedule for yourself, take another look at it and see where you can heighten your efficiency to stay organized and optimized.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOM', 'title' => 'Simplify Your Commitments', 'description' => `Review your commitments today and consider simplifying or eliminating those that no longer serve you. Your Creating Order driver will thrive as you free up time and energy.`, 'created_at' => now(), 'updated_at' => now()],

//            FE seeder
            ['code' => 'FE', 'title' => 'Prepare a First Aid Kit', 'description' => `Your Creating Protection driver provides you with the natural ability to recognize how to be prepared in many aspects of life. Today, ensure you have a well-stocked first aid kit and general emergency supplies at home and in your car. Place the kits in visible and accessible locations and set reminders to check them regularly.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Update Emergency Contacts', 'description' => `Spend time today updating your emergency contact list. Set an intention to review and update it every six months, share it with family members and trusted friends, and store it both digitally and in a physical address book. This practice will “feed” your Creating Protection driver.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Develop a Safety Plan', 'description' => `Your Creating Protection driver aligns with safety. Today, begin to develop a comprehensive safety plan for your home and family, including emergency contacts, evacuation routes, and safety protocols. Schedule regular reviews and updates to keep the plan effective.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Foster Open Communication', 'description' => `Today, begin to share your understanding of your need to address safety concerns with a family member, a friend, or colleague. Explain that taking preventative measures is important to you; share that too much uncertainty around issues can even cause anxiety for you. Encourage open dialogue without labeling or judgment`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Limit Exposure to Negative News', 'description' => `To maintain the strong state of your Creating Protection driver, designate specific times to check the news (particularly not first thing in the morning or just before you go to sleep) and avoid information overload. Choose reliable sources, balance news intake with positive content, and discuss concerns with trusted individuals.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Utilize Safety Technology', 'description' => `Leverage technology for peace of mind, as you “feed” your Creating Protection driver. Today, consider installing safety apps, using smart home devices, and keeping software updated. Remind yourself to regularly update passwords and enable two-factor authentication to protect personal information. Any or all of these actions will Create Protection for you.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Prioritize Self-Care and Relaxation', 'description' => `To stay in the strong state of your Creating Protection driver, ensure you're getting enough sleep, eating well, and staying hydrated. Today, set aside time for yourself to engage in activities that align with your interests and practice relaxation techniques.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Perform Essential Safety Actions', 'description' => `  <p>Because you have <strong>Creating Protection</strong> as one of your drivers, today, choose at least one action to enhance safety:</p>

    <ul>
        <li>Check tire pressure and oil levels on your car.</li>
        <li>Give a spare set of keys to a trusted person.</li>
        <li>Check expiration dates on medications and restock as needed.</li>
        <li>Place spare phone chargers in your car, office, and home.</li>
        <li>Store flashlights in multiple locations around your home.</li>
        <li>Program emergency contacts into your phone's speed dial.</li>
        <li>Post a list of emergency numbers near landlines.</li>
        <li>Designate a safe space in your home for relaxation and security.</li>
    </ul>`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Gather Information to Ease Anxiety', 'description' => `The weak state of your Creating Protection driver can get anxious, and if not addressed, this can escalate into feelings of panic. If you're feeling anxious today (or any day), spend time aligning with resources that support your ability to create protection. Whatever you are anxious about, seek information from reputable sources to ensure you have all the information, talk to a trusted family member, friend or colleague and share your feelings, only consume content that provides clarity and relief.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Stay Hydrated and Nourished', 'description' => `Today, support your Creating Protection driver by maintaining good hydration and nutrition to keep your body functioning optimally, enhancing your resilience.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FE', 'title' => 'Establish a Daily Safety Check', 'description' => `Today, set an intention to inspect your home or workspace for potential hazards. Set a specific time each day, (or each month or year), make a short checklist of items to review (like locks, oven or stoves left on, smoke detectors, electrical outlets, carbon monoxide detectors), and address any issues promptly.`, 'created_at' => now(), 'updated_at' => now()],

//            GRE seeder

            ['code' => 'GRE', 'title' => 'Review Your Budget Weekly', 'description' => `Because you have Monetary Discernment driving you, set a weekly reminder to review your budget. Track your income and expenses to ensure a harmonious flow of money.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Allocate Time for Financial Planning', 'description' => `Set aside time today (and several times a week) for financial planning. This practice will fuel your Monetary Discernment driver and keep you optimized.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Engage in Charitable Giving', 'description' => `Begin a practice of consistent tithing or charitable giving. This will fuel the strong state of your Monetary Discernment driver and enhance your sense of contribution.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Monitor Your Credit Score Monthly', 'description' => `Calendar a date every month to monitor your credit score. Keeping an eye on your credit will help you maintain financial health and fuel your Monetary Discernment driver.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Optimize the Flow of Money', 'description' => `Consider where you can optimize the harmonious flow of money in your life. Use budgeting apps to create an optimal budget and track your daily expenses. This will ensure you stay in the strong state of your Monetary Discernment driver.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Declutter and Purge Excess Items', 'description' => `Harmonious flow isn't just about money; it also relates to possessions. Today, consider decluttering your space by removing items you no longer need, restoring balance.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Reinvest Profits for Growth', 'description' => `Your Monetary Discernment driver understands that it takes money to make money. Today, consider where you can reinvest your profits into growth opportunities to enhance your financial position.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Explore Passive Income Opportunities', 'description' => `Seek opportunities for passive income to enhance your financial portfolio. Today, set aside some time to research options like real estate, dividends, or other investments.  These opportunities (and others) “feed” the strong state of your Monetary Discernment driver.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Automate Your Savings', 'description' => `Today, if you’re not already doing so, consider automating your savings to ensure consistent contributions to your emergency fund, retirement accounts, and investment portfolios.  This is a great way to “feed” your Monetary Discernment driver. `, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Recognize Signs of Gluttony', 'description' => `Be mindful of the weak state of your Monetary Discernment driver, which is gluttony. Reflect on areas where you may be overindulging and take steps to restore harmony.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GRE', 'title' => 'Review Subscriptions and Memberships', 'description' => `Today, take some time and evaluate recurring expenses like subscriptions and memberships. Make a choice to cancel those that no longer provide value to optimize your spending.  This strategy “feeds” your Monetary Discernment driver. `, 'created_at' => now(), 'updated_at' => now()],

//            LUN seeder

            ['code' => 'LUN', 'title' => 'Embrace Your Natural Impulses', 'description' => `Because you have spontaneity as one of your drivers, allow yourself to act on a sudden idea today without overthinking it. This could lead to a new creative breakthrough.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Start an Idea Journal', 'description' => `Your spontaneity driver provides you with endless, outside-the-box ideas. Today, start an idea journal. Keep it handy to capture your thoughts whenever an idea “pops in.”`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Use Voice Memos', 'description' => `Because your ideas can be fleeting, use voice memos today to record your thoughts as they come. This will help you manage and revisit your spontaneous insights.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Dedicate Time to Creative Activities', 'description' => `Your spontaneity driver thrives on creativity. Dedicate time today to any creative activity you enjoy to keep your genius nourished.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Seek Innovative Environments', 'description' => `Seek out environments today that encourage innovation and idea sharing. This will help you stay in a strong state by feeding your spontaneity driver.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Raise Your Serotonin Levels', 'description' => `Raise your serotonin levels today by spending time in sunlight and engaging in physical activities. This will help harmonize your spontaneity driver and prevent manic swings from gaining traction.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Communicate in Judgment-Free Spaces', 'description' => `Today, focus on communicating your ideas in judgment-free spaces; align with people in your life who are kind, accepting, and inclusive. This will prevent feelings of being misunderstood, which can lead to manic states.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Take Micro Moments for Unplanned Activities', 'description' => `Because you thrive on spontaneity, take micro moments throughout the day to do something unplanned, like a quick walk or engaging in a hobby.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Channel Energy through Expressive Arts', 'description' => `Use expressive arts today like painting, drawing, or music to channel your spontaneous energy into tangible forms. This will help prevent feelings of being overwhelmed.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Engage in Discussions with Diverse Groups', 'description' => `Your spontaneity driver provides you with unique perspectives. Today, seek to engage in discussions with diverse groups to broaden your understanding and refine your ideas.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LUN', 'title' => 'Connect with Nature', 'description' => `To help stabilize and harmonize your spontaneity driver and to calm thoughts, spend time in nature today. Walk barefoot on grass, lean against a tree, or simply enjoy the outdoors.`, 'created_at' => now(), 'updated_at' => now()],

//             NAI seeder
            ['code' => 'NAI', 'title' => 'Thankfulness', 'description' => `Because you have Optimism driving you, spend some time today recognizing what you are thankful for in your life. Write down three things you are thankful for today, share one with a friend or family member, and reflect on how this thankfulness exercise impacts your day.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'See Opportunities in Challenges', 'description' => `Your Optimism driver provides you with the ability to identify opportunities within the challenges of life. Today, identify one challenge you are facing, list three possible positive outcomes from this challenge, and take one small step towards achieving one of these outcomes.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'Surround Yourself with Positivity', 'description' => `Because you have Optimism driving you, surrounding yourself with positivity is important. Today, spend time with people who uplift and inspire you, listen to motivational podcasts or music, or play with a child or animal.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'Spread Good Cheer', 'description' => `Your Optimism driver encourages you to spread good cheer. Today, perform a random act of kindness for someone, compliment a colleague or friend sincerely, or share a positive story or joke with someone.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'Find Silver Linings', 'description' => `Because you have Optimism driving you, you can find the silver lining in most situations. As you go about your day, tune into when something not so optimal occurs. When it does, find one opportunity in what occurred and share this with someone involved in the situation.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'Replace Immaturity with Optimism', 'description' => `When you are not "fueling" your Optimism driver, you may exhibit immature behavior. Today, pay attention to any immature thoughts or feelings. If you recognize that you've been deflated, quickly replace immaturity with an optimistic activity to restore your energy.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'Create Fun and Excitement', 'description' => `Because you have Optimism driving you, create some fun and excitement in your activities today. Turn a mundane task into a game or challenge, plan a surprise for someone you care about, or add an element of fun to your work environment.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'Perform Random Acts of Kindness', 'description' => `Your Optimism driver encourages you to participate in random acts of kindness. Today, open the door for someone, smile at someone, or leave an uplifting note for someone to find.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'Foster Positive Relationships', 'description' => `Your Optimism driver encourages you to create possibility-filled solutions in relationships. Discuss future plans and dreams with a partner or friend, work together to uncover a solution to a problem, or celebrate a shared success or milestone.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAI', 'title' => 'Engage in Playful Activities', 'description' => `Because you have Optimism driving you, engage in playful activities today. Spend time playing with children or pets, visit a local amusement park or recreational area, or have a game night with friends or family.`, 'created_at' => now(), 'updated_at' => now()],

//            NE seeder

            ['code' => 'NE', 'title' => 'Practice Active Listening', 'description' => `Because you have Humility driving you, you are a natural listener. Today, practice active listening by focusing on the speaker without interrupting. Reflect back what you hear to ensure understanding and ask open-ended questions to encourage deeper conversation.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Recognize When to Recharge', 'description' => `Your Humility driver needs to find the harmony between engaging with others and stepping away to recharge. Today, practice recognizing when it’s time for you to recharge. Set aside specific times for solitude and communicate your need for alone time to those around you.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Be a Grounding Presence', 'description' => `Your Humility driver is naturally grounding for others. Today, offer support and reassurance to someone during a stressful time. Be the calming presence in chaotic environments and provide a listening ear without judgment.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Maintain Balance to Avoid Neglect', 'description' => `The weak state of your Humility driver is neglect. Today, reflect on what the harmony between engaging with others and taking time for yourself looks like for you. Recognize signs when you've been "on" too long with others or when you've been in recharge mode (away from others) too long, and adjust accordingly.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Educate Others About Your Needs', 'description' => `Because you have Humility as one of your drivers, educate another (or others) today on your need for recharge time. Explain the importance of alone time for your well-being, set boundaries around your availability, and encourage loved ones to respect your need for solitude.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Learn to Say "No" When Necessary', 'description' => `Your Humility driver often impacts your ability to say "no." Today, pay attention to what you say "yes" to, ensuring that you are not overextending yourself. Practice politely declining requests that overfill your plate.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Connect with Nature', 'description' => `You easily connect with nature, which is reviving and rejuvenating for you. Today, spend time outdoors in a place that brings you peace. Consider exploring new natural environments and make a plan to spend consistent time in nature.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Be Mindful of Being Taken Advantage Of', 'description' => `Your graciousness is a fine quality, but it can sometimes lead others to take advantage of you. Today, be mindful of agreeing to things out of obligation rather than desire. Ensure that your commitments align with your well-being.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Balance Engagement and Solitude', 'description' => `To maintain harmony with your Humility driver, balance your time between social interactions and solitude. Monitor your energy levels to prevent burnout and adjust your schedule to include both engagement and recharge time.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NE', 'title' => 'Embrace Your Talents Modestly', 'description' => `There is a modesty that exists in your Humility driver. Today, rather than dismissing your talents, reflect on how they benefit others. Accept compliments graciously and use your strengths to support and uplift those around you.`, 'created_at' => now(), 'updated_at' => now()],

//            POW seeder
            ['code' => 'POW', 'title' => 'Break Down Big Goals', 'description' => `Because you have Accomplishment as one of your drivers, consider the big goals you have for yourself. Today, spend time breaking those goals into smaller, manageable tasks that can be accomplished today.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Track Your Progress', 'description' => `With Accomplishment as one of your drivers, winning is important to you. Begin tracking your progress today by keeping a journal or using an app to log daily achievements and reflect on your progress.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Celebrate Small Victories', 'description' => `Your Accomplishment driver motivates you to set lofty goals. Today, celebrate your small victories by acknowledging and rewarding yourself for recent achievements to maintain energy and enthusiasm.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Commit to a New Habit', 'description' => `Your Accomplishment driver provides you with a strong work ethic. Today, commit to one new habit that directly supports your goal-oriented lifestyle.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Set Realistic Benchmarks', 'description' => `Because you have Accomplishment as a driver, today review or refine your benchmarks related to your most important goal. Ensure that your goals are challenging yet attainable.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Schedule Goal-Setting Sessions', 'description' => `Your Accomplishment driver needs goals as your oxygen. Today, schedule a goal-setting session and dedicate time each week to review and adjust your goals.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => `Respect Others' Perspectives`, 'description' => `Remember that not everyone shares your drive for accomplishment. Today, pay attention to others' perspectives without judgment and avoid imposing your standards on them.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Create a Backup Goals List', 'description' => `Because your Accomplishment driver is naturally restless without objectives, begin a list of backup goals today. These are alternative goals you can pursue if you complete your primary ones early.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Seek Feedback', 'description' => `Seek feedback or input from trusted peers to refine your strategies and improve outcomes. This collaboration can enhance your effectiveness.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Embrace Your Drive for Accomplishment', 'description' => `Today, take a moment and recognize and appreciate your innate drive to achieve. Use it as a powerful force to propel you toward your goals.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Reflect on Daily Accomplishments', 'description' => `With Accomplishment as one of your driving forces, at the end of your day today, reflect on what you've accomplished and plan for the next day.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'POW', 'title' => 'Review Goals Regularly', 'description' => `With Accomplishment as one of your drivers, take time today to assess your current goals to ensure they remain aligned with your vision.`, 'created_at' => now(), 'updated_at' => now()],

//            SP seeder
            ['code' => 'SP', 'title' => 'Care for a Living Being', 'description' => `<p>Your <strong>Compassion</strong> driver encourages you to care for living things. Today, choose at least one activity that allows you to care for the needs of a person, plant, or animal. Suggestions include:</p>

    <ul>
        <li>Do something helpful for someone.</li>
        <li>Spend time gardening or watering houseplants.</li>
        <li>Walk or play with a pet.</li>
    </ul>
`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Reconnect with Others', 'description' => `Your Compassion driver seeks to be helpful to others. Today, reach out to a friend you haven't spoken to in a while, organize a small gathering to foster connections, or join a community group with shared interests.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Offer Assistance', 'description' => `<p>Because your <strong>Compassion</strong> driver thrives on helping others, offer your assistance to someone today. You might:</p>

    <ul>
        <li>Help a neighbor with a task or chore.</li>
        <li>Offer your skills or expertise to someone in need.</li>
        <li>Be available to listen and support those around you.</li>
    </ul>`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => `Be Aware of Others' Needs`, 'description' => `Your Compassion driver encourages you to be aware of others' needs. Today, anticipate the needs of those around you. Offer help before being asked and be considerate of others' feelings and circumstances.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Perform Acts of Kindness', 'description' => `<p>Because you have <strong>Compassion</strong> driving you, caring for others is a primary focus. Today, engage in one or more acts of kindness, such as:</p>
    <ul>
        <li>Performing a random act of kindness for a stranger.</li>
        <li>Complimenting someone genuinely.</li>
        <li>Sending a "thinking of you" card to someone.</li>
    </ul>`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Explore Ways to Serve Your Community', 'description' => `<p>Your <strong>Compassion</strong> driver thrives on being of service to others. Today, explore ways you could serve your community:</p>

    <ul>
        <li>Find a local charity or organization that aligns with your values.</li>
        <li>Dedicate a specific time each week to volunteer.</li>
        <li>Encourage a friend to join you in volunteering.</li>
    </ul>`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Reflect on How You Care for Others', 'description' => `The weak state of your Compassion driver is "woe-is-me." This feeling arises when you don't provide yourself with enough opportunities to care for others. Today, set aside time to write down the different ways you care for living things. Use this list as a resource to remind yourself to engage with life in compassionate ways.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Practice Self-Care', 'description' => `<p>Because you care deeply about outcomes, disappointment can hit hard. To avoid feeling overwhelmed, it's important to practice self-care. Today (and every day):</p>

    <ul>
        <li>Set aside 15 minutes for relaxation.</li>
        <li>Make healthy food choices.</li>
        <li>Stay properly hydrated.</li>
        <li>Ensure you get enough sleep.</li>
    </ul>`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Avoid Self-Sacrifice', 'description' => `Your Compassion driver thrives when being of service, but there's a fine line between serving others and sacrificing yourself. Today, consider ways you may have overextended yourself in the past. Remind yourself that you can help others without neglecting your own needs.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SP', 'title' => 'Make a Difference Today', 'description' => `<p>Focus on making a difference in someone else's life - it’s “fuel” for your <strong>Compassion</strong> driver. Do something nice and helpful for someone. Suggestions include:</p>

    <ul>
        <li>Lend a supportive ear to someone who needs to talk.</li>
        <li>Send a loving note, text, or email to someone.</li>
        <li>Give a thoughtful gift to someone.</li>
        <li>Bring a meal or dessert to a friend or family member.</li>
    </ul>`, 'created_at' => now(), 'updated_at' => now()],

//            TRA seeder
            ['code' => 'TRA', 'title' => 'Diversify Your Day', 'description' => `Your Traveler driver thrives on variety. Switch up how you engage in your daily activities today (and every day) to keep things fresh and exciting.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Try a New Hobby', 'description' => `Your Traveler driver provides you with a love for exploration. Dedicate time each week to try a new hobby or activity.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Attend Local Events', 'description' => `Your Traveler driver relishes new experiences. Today, check out an event calendar for your area. Plan to attend the next cultural event, concert, festival, or exhibition that interests you.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Change Your Work Setting', 'description' => `To keep your professional life varied, and your Traveler driver optimized, set an intention to change your work setting occasionally. Starting today! Work from a different space within your home or office, or visit a coffee shop, café, or co-working space.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Incorporate Varied Exercise', 'description' => `When it comes to exercise, your Traveler driver needs daily variety. Choose a different type of physical activity today —like walking, hiking, dancing, or any activity that provides a new experience.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Discover New Media', 'description' => `Take a break today and discover new music, podcasts, or virtual experiences that align with your interests. This will nourish your Traveler driver and keep you energized.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Take a New Route', 'description' => `Because your Traveler driver draws you to adventure, take a new route home from work today. If you have more time, embark on a day excursion to a nearby town or nature spot.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Experiment with Cuisine', 'description' => `Your Traveler driver loves diversity. Today, experiment with cooking a recipe from a different cuisine or visit a new restaurant.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Vary Your Entertainment', 'description' => `To keep your entertainment diverse, vary your media consumption. Today, watch a different genre of movie or TV show, or explore a new podcast.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Plan a Trip', 'description' => `Your Traveler driver loves to travel! Take time today to explore your next travel destination, whether it's a big adventure or a variety-filled "staycation."  Write down a list of places you want to visit or stay.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRA', 'title' => 'Connect with New People', 'description' => `Your Traveler driver loves variety. Engage in conversations with someone new today. Networking can open doors to fresh experiences and perspectives.`, 'created_at' => now(), 'updated_at' => now()],

//            VAN seeder
            ['code' => 'VAN', 'title' => 'Appreciate Beauty Today', 'description' => `Because you have Aesthetic Sensibility driving you, spend time today appreciating a piece of art, music, or something beautiful in nature. This will feed your need for beauty.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Dress Expressively', 'description' => `Your appreciation for beauty can be accessed in all areas of life, including your daily attire. Today, take time to dress in a way that makes you feel confident and expressive, boosting your mood and self-esteem.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Seek Opportunities to Perform', 'description' => `Because your Aesthetic Sensibility is performance-oriented, seek opportunities today, and every day, to present your talents to the world. This could be through sports, creative arts, music, dance, speaking, or design.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Give Genuine Compliments', 'description' => `Your Aesthetic Sensibility driver is energized by positive reception. Today, practice giving genuine compliments to others to foster a supportive environment where you also receive acknowledgment.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Curate a Personal Collection', 'description' => `Begin curating a personal collection of beautiful things like books, art, photography, or music that inspire you. Surrounding yourself with beauty energizes and optimizes you.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Explore Places of Beauty', 'description' => `Because you have a keen eye for aesthetics, explore or visit a place of beauty today that inspires you, such as an art gallery, scenic park, or unique café.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Share Your Creative Talents', 'description' => `Your Aesthetic Sensibility driver thrives when you share your gifts and receive feedback. Today, share your creative talents with a friend or online community and notice how the feedback makes you feel.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Be Aware of Self-Absorption', 'description' => `Pay attention today to moments when you find yourself longing for or seeking feedback, attention, or praise from others. Recognize that seeking validation indicates you are operating in the weak state of self-absorption. To get back into the strong state of your Aesthetic Sensibility driver, give yourself an opportunity to present, perform or simply engage with others.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Balance Sharing and Listening', 'description' => `Today, set an intention and begin cultivating an awareness around how much you talk about yourself and ensure you allow others to share as well. Engaging in balanced conversations prevents falling into the weak state of your Aesthetic Sensibility driver …self-absorption.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Engage in Creative Activities', 'description' => `Today, to “feed” your Aesthetic Sensibility driver, provide yourself with opportunities to create beauty. Engage in activities that allow you to perform, present, or express without the pressured need for external validation.`, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VAN', 'title' => 'Decorate Your Space', 'description' => `Today, do one thing to enhance the beauty of your living or working space. Your Aesthetic Sensibility driver is energized when it creates beauty of any kind. `, 'created_at' => now(), 'updated_at' => now()],

//            WIL seeder

            ['code' => 'WIL', 'title' => '', 'description' => ``, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WIL', 'title' => '', 'description' => ``, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WIL', 'title' => '', 'description' => ``, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WIL', 'title' => '', 'description' => ``, 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'WIL', 'title' => '', 'description' => ``, 'created_at' => now(), 'updated_at' => now()],
        ];
    }
}
