<?php

namespace Database\Seeders;

use App\Enums\Admin\Admin;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OptimizationPlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('optimization_plan')->truncate();

        $fourteenDaysPlan = [

            ['priority' => 'priority_1', 'condition' => 'Aesthetic Sensibility is 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_1'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_regal', 'condition' => 'Regal is 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_2.regal'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_energetic', 'condition' => 'Energetic is 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_2.energetic'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_absorptive', 'condition' => 'Absorptive is 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_2.absorptive'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_romantic', 'condition' => 'Romantic is 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_2.romantic'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_sympathetic', 'condition' => 'Sympathetic is 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_2.sympathetic'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_perceptive', 'condition' => 'Perceptive is 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_2.perceptive'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_effervescent', 'condition' => 'Effervescent is 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_2.effervescent'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_3', 'condition' => 'IF [JO & MER MAIN VOLUME are all <5] AND [BOTH JO and MER have a Weight of <30] AND [SO MAIN VOLUME is < 3]', 'fourteen_days_plan' => config('14DaysActionPlan.priority_3'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_4', 'condition' => 'IF the number of AUTHENTIC TRAITS (Green Boxes) is less than (<) 3', 'fourteen_days_plan' => config('14DaysActionPlan.priority_4'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_5', 'condition' => 'IF [MA and LU MAIN VOLUME are both <5] AND [BOTH MA And LU have a Weight of <30]', 'fourteen_days_plan' => config('14DaysActionPlan.priority_5'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_6', 'condition' => 'IF [SA and VEN MAIN VOLUMES are BOTH <5] AND [BOTH SA And VEN have a VOLUME of <30]', 'fourteen_days_plan' => config('14DaysActionPlan.priority_6'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_7', 'condition' => 'IF there are 4+ INAUTHENTIC DRIVERS (4+ Red Boxes)', 'fourteen_days_plan' => config('14DaysActionPlan.priority_7'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_8', 'condition' => 'IF there are exactly THREE (3) Drivers that are INAUTHENTIC DRIVERS (3 Red Boxes) ', 'fourteen_days_plan' => config('14DaysActionPlan.priority_8'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_9', 'condition' => 'IF there are exactly TWO (2) Drivers that are INAUTHENTIC DRIVERS (2 Red Boxes) ', 'fourteen_days_plan' => config('14DaysActionPlan.priority_9'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_10', 'condition' => 'IF there is exactly ONE (1) Driver that is an INAUTHENTIC DRIVER (1 Red Box)', 'fourteen_days_plan' => config('14DaysActionPlan.priority_10'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_11', 'condition' => 'IF both PILOT and CO-PILOT (Green Boxes) DRIVERS are LESS THAN (<) 3 in MAIN VOLUME.', 'fourteen_days_plan' => config('14DaysActionPlan.priority_11'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_12', 'condition' => 'IF JUST ONE of the PILOT or CO-PILOT (Green Box) Drives is LESS THAN (<) 3 in MAIN VOLUME…', 'fourteen_days_plan' => config('14DaysActionPlan.priority_12'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_13', 'condition' => 'IF total of MAIN VOLUME (1st Row) of ALL Drivers is GREATER THAN (>) 21', 'fourteen_days_plan' => config('14DaysActionPlan.priority_13'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_14', 'condition' => 'IF total MAIN VOLUME (1st Row) of ALL DRIVERS is LESS THAN (<) 16', 'fourteen_days_plan' => config('14DaysActionPlan.priority_14'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_15', 'condition' => 'IF the Alchemy number is ANY ONE of these numbers: 700, 610, 601, 520, 511, 502, 430', 'fourteen_days_plan' => config('14DaysActionPlan.priority_15'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_16', 'condition' => 'IF the Alchemy number is ANY ONE of these numbers: 223, 133, 043, 214, 124, 115, 034, 007', 'fourteen_days_plan' => config('14DaysActionPlan.priority_16'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_17', 'condition' => 'IF ANY TWO (2) of the Energy Center (EM, INS, INT, or MOV) are GREATER THAN (>) 12 (1st Row)', 'fourteen_days_plan' => config('14DaysActionPlan.priority_17'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_18', 'condition' => 'IF ANY ONE (1) of the Energy Center (EM, INS, INT, or MOV) is GREATER THAN (>) 12 (1st Row)', 'fourteen_days_plan' => config('14DaysActionPlan.priority_18'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_19', 'condition' => 'IF ANY TWO (2) of the Energy Center (EM, INS, INT, or MOV) are LESS THAN (<) 7 (1st Row)', 'fourteen_days_plan' => config('14DaysActionPlan.priority_19'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_20', 'condition' => 'IF ANY ONE (1) of the Energy Center (EM, INS, INT, or MOV) is LESS THAN (<) 7 (1st Row)', 'fourteen_days_plan' => config('14DaysActionPlan.priority_20'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_21', 'condition' => 'IF the PV# = 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_21'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_22', 'condition' => 'IF the PV# < 0', 'fourteen_days_plan' => config('14DaysActionPlan.priority_22'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_23', 'condition' => 'IF the PV# > 12', 'fourteen_days_plan' => config('14DaysActionPlan.priority_23'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_24', 'condition' => 'IF the EP# < 25', 'fourteen_days_plan' => config('14DaysActionPlan.priority_24'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_25', 'condition' => 'IF the EP# > 35', 'fourteen_days_plan' => config('14DaysActionPlan.priority_25'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_26', 'condition' => 'If ALL the above conditions are FALSE then use the following 90-Day Optimization Action Plan', 'fourteen_days_plan' => config('14DaysActionPlan.priority_26'), 'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],

        ];

        $nintyDaysPlan = [

            ['priority' => 'priority_1', 'condition' => 'Aesthetic Sensibility is 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_1.intro'), 'day1_30' => config('90DaysActionPlan.priority_1.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_1.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_1.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_regal', 'condition' => 'Regal is 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_2.regal.intro'), 'day1_30' => config('90DaysActionPlan.priority_2.regal.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_2.regal.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_2.regal.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_energetic', 'condition' => 'Energetic is 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_2.energetic.intro'), 'day1_30' => config('90DaysActionPlan.priority_2.energetic.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_2.energetic.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_2.energetic.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_absorptive', 'condition' => 'Absorptive is 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_2.absorptive.intro'), 'day1_30' => config('90DaysActionPlan.priority_2.absorptive.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_2.absorptive.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_2.absorptive.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_romantic', 'condition' => 'Romantic is 0', 'ninty_days_plan' => config('14DaysActionPlan.priority_2.romantic.intro'), 'day1_30' => config('90DaysActionPlan.priority_2.romantic.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_2.romantic.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_2.romantic.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_sympathetic', 'condition' => 'Sympathetic is 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_2.sympathetic.intro'), 'day1_30' => config('90DaysActionPlan.priority_2.sympathetic.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_2.sympathetic.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_2.sympathetic.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_perceptive', 'condition' => 'Perceptive is 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_2.perceptive.intro'), 'day1_30' => config('90DaysActionPlan.priority_2.perceptive.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_2.perceptive.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_2.perceptive.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_effervescent', 'condition' => 'Effervescent is 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_2.effervescent.intro'), 'day1_30' => config('90DaysActionPlan.priority_2.effervescent.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_2.effervescent.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_2.effervescent.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_3', 'condition' => 'IF [JO & MER MAIN VOLUME are all <5] AND [BOTH JO and MER have a WEIGHT of <30] AND [SO MAIN VOLUME is < 3]', 'ninty_days_plan' => config('90DaysActionPlan.priority_3.intro'), 'day1_30' => config('90DaysActionPlan.priority_3.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_3.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_3.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_4', 'condition' => 'IF the number of AUTHENTIC TRAITS (Green Boxes) is less than (<) 3', 'ninty_days_plan' => config('90DaysActionPlan.priority_4.intro'), 'day1_30' => config('90DaysActionPlan.priority_4.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_4.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_4.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_5', 'condition' => 'IF [MA and LU MAIN VOLUME are both <5] AND [BOTH MA And LU have a Weight of <30]', 'ninty_days_plan' => config('90DaysActionPlan.priority_5.intro'), 'day1_30' => config('90DaysActionPlan.priority_5.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_5.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_5.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_6', 'condition' => 'IF [SA and VEN MAIN VOLUMES are BOTH <5] AND [BOTH SA And VEN have a VOLUME of <30]', 'ninty_days_plan' => config('90DaysActionPlan.priority_6.intro'), 'day1_30' => config('90DaysActionPlan.priority_6.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_6.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_6.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_7', 'condition' => 'IF there are 4+ INAUTHENTIC DRIVERS (4+ Red Boxes)', 'ninty_days_plan' => config('90DaysActionPlan.priority_7.intro'), 'day1_30' => config('90DaysActionPlan.priority_7.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_7.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_7.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_8', 'condition' => 'IF there are exactly THREE (3) Drivers that are INAUTHENTIC DRIVERS (3 Red Boxes) ', 'ninty_days_plan' => config('90DaysActionPlan.priority_8.intro'), 'day1_30' => config('90DaysActionPlan.priority_8.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_8.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_8.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_9', 'condition' => 'IF there are exactly TWO (2) Drivers that are INAUTHENTIC DRIVERS (2 Red Boxes) ', 'ninty_days_plan' => config('90DaysActionPlan.priority_9.intro'), 'day1_30' => config('90DaysActionPlan.priority_9.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_9.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_9.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_10', 'condition' => 'IF there is exactly ONE (1) Driver that is an INAUTHENTIC DRIVER (1 Red Box)', 'ninty_days_plan' => config('90DaysActionPlan.priority_10.intro'), 'day1_30' => config('90DaysActionPlan.priority_10.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_10.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_10.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_11', 'condition' => 'IF both PILOT and CO-PILOT (Green Boxes) DRIVERS are LESS THAN (<) 3 in MAIN VOLUME.', 'ninty_days_plan' => config('90DaysActionPlan.priority_11.intro'), 'day1_30' => config('90DaysActionPlan.priority_11.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_11.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_11.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_12', 'condition' => 'IF JUST ONE of the PILOT or CO-PILOT (Green Box) Drives is LESS THAN (<) 3 in MAIN VOLUME…', 'ninty_days_plan' => config('90DaysActionPlan.priority_12.intro'), 'day1_30' => config('90DaysActionPlan.priority_12.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_12.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_12.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_13', 'condition' => 'IF total of MAIN VOLUME (1st Row) of ALL Drivers is GREATER THAN (>) 21', 'ninty_days_plan' => config('90DaysActionPlan.priority_13.intro'), 'day1_30' => config('90DaysActionPlan.priority_13.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_13.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_13.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_14', 'condition' => 'IF total MAIN VOLUME (1st Row) of ALL DRIVERS is LESS THAN (<) 16', 'ninty_days_plan' => config('90DaysActionPlan.priority_14.intro'), 'day1_30' => config('90DaysActionPlan.priority_14.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_14.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_14.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_15', 'condition' => 'IF the Alchemy number is ANY ONE of these numbers: 700, 610, 601, 520, 511, 502, 430', 'ninty_days_plan' => config('90DaysActionPlan.priority_15.intro'), 'day1_30' => config('90DaysActionPlan.priority_15.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_15.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_15.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_16', 'condition' => 'IF the Alchemy number is ANY ONE of these numbers: 223, 133, 043, 214, 124, 115, 034, 007', 'ninty_days_plan' => config('90DaysActionPlan.priority_16.intro'), 'day1_30' => config('90DaysActionPlan.priority_16.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_16.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_16.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_17', 'condition' => 'IF ANY TWO (2) of the Energy Center (EM, INS, INT, or MOV) are GREATER THAN (>) 12 (1st Row)', 'ninty_days_plan' => config('90DaysActionPlan.priority_17.intro'), 'day1_30' => config('90DaysActionPlan.priority_17.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_17.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_17.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_18', 'condition' => 'IF ANY ONE (1) of the Energy Center (EM, INS, INT, or MOV) is GREATER THAN (>) 12 (1st Row)', 'ninty_days_plan' => config('90DaysActionPlan.priority_18.intro'), 'day1_30' => config('90DaysActionPlan.priority_18.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_18.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_18.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_19', 'condition' => 'IF ANY TWO (2) of the Energy Center (EM, INS, INT, or MOV) are LESS THAN (<) 7 (1st Row)', 'ninty_days_plan' => config('90DaysActionPlan.priority_19.intro'), 'day1_30' => config('90DaysActionPlan.priority_19.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_19.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_19.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_20', 'condition' => 'IF ANY ONE (1) of the Energy Center (EM, INS, INT, or MOV) is LESS THAN (<) 7 (1st Row)', 'ninty_days_plan' => config('90DaysActionPlan.priority_20.intro'), 'day1_30' => config('90DaysActionPlan.priority_20.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_20.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_20.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_21', 'condition' => 'IF the PV# = 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_21.intro'), 'day1_30' => config('90DaysActionPlan.priority_21.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_21.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_21.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_22', 'condition' => 'IF the PV# < 0', 'ninty_days_plan' => config('90DaysActionPlan.priority_22.intro'), 'day1_30' => config('90DaysActionPlan.priority_22.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_22.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_22.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_23', 'condition' => 'IF the PV# > 12', 'ninty_days_plan' => config('90DaysActionPlan.priority_23.intro'), 'day1_30' => config('90DaysActionPlan.priority_23.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_23.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_23.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_24', 'condition' => 'IF the EP# < 25', 'ninty_days_plan' => config('90DaysActionPlan.priority_24.intro'), 'day1_30' => config('90DaysActionPlan.priority_24.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_24.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_24.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_25', 'condition' => 'IF the EP# > 35', 'ninty_days_plan' => config('90DaysActionPlan.priority_25.intro'), 'day1_30' => config('90DaysActionPlan.priority_25.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_25.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_25.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_26', 'condition' => 'If ALL the above conditions are FALSE then use the following 90-Day Optimization Action Plan', 'ninty_days_plan' => config('90DaysActionPlan.priority_26.intro'), 'day1_30' => config('90DaysActionPlan.priority_26.day1_30'), 'day31_60' => config('90DaysActionPlan.priority_26.day31_60'), 'day61_90' => config('90DaysActionPlan.priority_26.day61_90'), 'type' => Admin::NINETY_DAYS_ACTION_PLAN, 'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],

        ];

        DB::table('optimization_plan')->insert($fourteenDaysPlan);
        DB::table('optimization_plan')->insert($nintyDaysPlan);
    }
}
