<?php

namespace Database\Seeders;

use App\Enums\Admin\Admin;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OptimizationPlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('optimization_plan')->truncate();

        $plan = [

            // =========================  14 Days Action Plans for Freemium  ============================== //
            ['priority' => 'priority_1','condition' => 'Aesthetic Sensibility is 0','content' => config('14DaysActionPlan.priority_1'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_regal','condition' => 'Regal is 0','content' => config('14DaysActionPlan.priority_2.regal'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_energetic','condition' => 'Energetic is 0','content' => config('14DaysActionPlan.priority_2.energetic'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_absorptive','condition' => 'Absorptive is 0','content' => config('14DaysActionPlan.priority_2.absorptive'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_romantic','condition' => 'Romantic is 0','content' => config('14DaysActionPlan.priority_2.romantic'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_sympathetic','condition' => 'Sympathetic is 0','content' => config('14DaysActionPlan.priority_2.sympathetic'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_perceptive','condition' => 'Perceptive is 0','content' => config('14DaysActionPlan.priority_2.perceptive'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_effervescent','condition' => 'Effervescent is 0','content' => config('14DaysActionPlan.priority_2.effervescent'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_3','condition' => 'IF [JO, MER, and SO MAIN VOLUME are all <5] AND [NEITHER JO or MER are BRIDGED] AND [JO, MER, and SO each have a 2ND TOGGLE VOLUME of <30]','content' => config('14DaysActionPlan.priority_3'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_4','condition' => 'IF the number of AUTHENTIC TRAITS (Green Boxes) is less than (<) 3','content' => config('14DaysActionPlan.priority_4'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_5','condition' => 'IF [MA and LU MAIN VOLUME are both <5] AND [NEITHER MA or LU are BRIDGED TRAITS] AND [Both MA And LU have a 2ND TOGGLE VOLUME of <30]','content' => config('14DaysActionPlan.priority_5'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_6','condition' => 'IF [SA and VEN MAIN VOLUMES are BOTH <5] AND [NEITHER SA or VEN are BRIDGED TRAITS] AND [BOTH SA And VEN have a 2ND TOGGLE VOLUME of <30]','content' => config('14DaysActionPlan.priority_6'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_7','condition' => 'IF there are 4+ INAUTHENTIC DRIVERS (4+ Red Boxes)','content' => config('14DaysActionPlan.priority_7'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_8','condition' => 'IF there are exactly THREE (3) Drivers that are INAUTHENTIC DRIVERS (3 Red Boxes) ','content' => config('14DaysActionPlan.priority_8'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_9','condition' => 'IF there are exactly TWO (2) Drivers that are INAUTHENTIC DRIVERS (2 Red Boxes) ','content' => config('14DaysActionPlan.priority_9'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_10','condition' => 'IF there is exactly ONE (1) Driver that is an INAUTHENTIC DRIVER (1 Red Box)','content' => config('14DaysActionPlan.priority_10'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_11','condition' => 'IF both PILOT and CO-PILOT (Green Boxes) DRIVERS are LESS THAN (<) 3 in MAIN VOLUME.','content' => config('14DaysActionPlan.priority_11'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_12','condition' => 'IF JUST ONE of the PILOT or CO-PILOT (Green Box) Drives is LESS THAN (<) 3 in MAIN VOLUME…','content' => config('14DaysActionPlan.priority_12'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_13','condition' => 'IF total of MAIN VOLUME (1st Row) of ALL Drivers is GREATER THAN (>) 21','content' => config('14DaysActionPlan.priority_13'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_14','condition' => 'IF total MAIN VOLUME (1st Row) of ALL DRIVERS is LESS THAN (<) 16','content' => config('14DaysActionPlan.priority_14'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_15','condition' => 'IF the Alchemy number is ANY ONE of these numbers: 700, 610, 601, 520, 511, 502, 430','content' => config('14DaysActionPlan.priority_15'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_16','condition' => 'IF the Alchemy number is ANY ONE of these numbers: 223, 133, 043, 214, 124, 115, 034, 007','content' => config('14DaysActionPlan.priority_16'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_17','condition' => 'IF ANY TWO (2) of the Energy Center (EM, INS, INT, or MOV) are GREATER THAN (>) 12 (1st Row)','content' => config('14DaysActionPlan.priority_17'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_18','condition' => 'IF ANY ONE (1) of the Energy Center (EM, INS, INT, or MOV) is GREATER THAN (>) 12 (1st Row)','content' => config('14DaysActionPlan.priority_18'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_19','condition' => 'IF ANY TWO (2) of the Energy Center (EM, INS, INT, or MOV) are LESS THAN (<) 7 (1st Row)','content' => config('14DaysActionPlan.priority_19'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_20','condition' => 'IF ANY ONE (1) of the Energy Center (EM, INS, INT, or MOV) is LESS THAN (<) 7 (1st Row)','content' => config('14DaysActionPlan.priority_20'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_21','condition' => 'IF the PV# = 0','content' => config('14DaysActionPlan.priority_21'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_22','condition' => 'IF the PV# < 0','content' => config('14DaysActionPlan.priority_22'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_23','condition' => 'IF the PV# > 12','content' => config('14DaysActionPlan.priority_23'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_24','condition' => 'IF the EP# < 25','content' => config('14DaysActionPlan.priority_24'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_25','condition' => 'IF the EP# > 35','content' => config('14DaysActionPlan.priority_25'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_26','condition' => 'If ALL the above conditions are FALSE then use the following 90-Day Optimization Action Plan','content' => config('14DaysActionPlan.priority_26'),'type' => Admin::FOURTEEN_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],


            // =========================  90 Days Action Plans for Paid  ============================== //
            ['priority' => 'priority_1','condition' => 'Aesthetic Sensibility is 0','content' => config('90DaysActionPlan.priority_1'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_regal','condition' => 'Regal is 0','content' => config('90DaysActionPlan.priority_2.regal'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_energetic','condition' => 'Energetic is 0','content' => config('90DaysActionPlan.priority_2.energetic'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_absorptive','condition' => 'Absorptive is 0','content' => config('90DaysActionPlan.priority_2.absorptive'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_romantic','condition' => 'Romantic is 0','content' => config('14DaysActionPlan.priority_2.romantic'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_sympathetic','condition' => 'Sympathetic is 0','content' => config('90DaysActionPlan.priority_2.sympathetic'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_perceptive','condition' => 'Perceptive is 0','content' => config('90DaysActionPlan.priority_2.perceptive'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_2_effervescent','condition' => 'Effervescent is 0','content' => config('90DaysActionPlan.priority_2.effervescent'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_3','condition' => 'IF [JO, MER, and SO MAIN VOLUME are all <5] AND [NEITHER JO or MER are BRIDGED] AND [JO, MER, and SO each have a 2ND TOGGLE VOLUME of <30]','content' => config('90DaysActionPlan.priority_3'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_4','condition' => 'IF the number of AUTHENTIC TRAITS (Green Boxes) is less than (<) 3','content' => config('90DaysActionPlan.priority_4'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_5','condition' => 'IF [MA and LU MAIN VOLUME are both <5] AND [NEITHER MA or LU are BRIDGED TRAITS] AND [Both MA And LU have a 2ND TOGGLE VOLUME of <30]','content' => config('90DaysActionPlan.priority_5'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_6','condition' => 'IF [SA and VEN MAIN VOLUMES are BOTH <5] AND [NEITHER SA or VEN are BRIDGED TRAITS] AND [BOTH SA And VEN have a 2ND TOGGLE VOLUME of <30]','content' => config('90DaysActionPlan.priority_6'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_7','condition' => 'IF there are 4+ INAUTHENTIC DRIVERS (4+ Red Boxes)','content' => config('90DaysActionPlan.priority_7'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_8','condition' => 'IF there are exactly THREE (3) Drivers that are INAUTHENTIC DRIVERS (3 Red Boxes) ','content' => config('90DaysActionPlan.priority_8'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_9','condition' => 'IF there are exactly TWO (2) Drivers that are INAUTHENTIC DRIVERS (2 Red Boxes) ','content' => config('90DaysActionPlan.priority_9'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_10','condition' => 'IF there is exactly ONE (1) Driver that is an INAUTHENTIC DRIVER (1 Red Box)','content' => config('90DaysActionPlan.priority_10'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_11','condition' => 'IF both PILOT and CO-PILOT (Green Boxes) DRIVERS are LESS THAN (<) 3 in MAIN VOLUME.','content' => config('90DaysActionPlan.priority_11'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_12','condition' => 'IF JUST ONE of the PILOT or CO-PILOT (Green Box) Drives is LESS THAN (<) 3 in MAIN VOLUME…','content' => config('90DaysActionPlan.priority_12'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_13','condition' => 'IF total of MAIN VOLUME (1st Row) of ALL Drivers is GREATER THAN (>) 21','content' => config('90DaysActionPlan.priority_13'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_14','condition' => 'IF total MAIN VOLUME (1st Row) of ALL DRIVERS is LESS THAN (<) 16','content' => config('90DaysActionPlan.priority_14'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_15','condition' => 'IF the Alchemy number is ANY ONE of these numbers: 700, 610, 601, 520, 511, 502, 430','content' => config('90DaysActionPlan.priority_15'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_16','condition' => 'IF the Alchemy number is ANY ONE of these numbers: 223, 133, 043, 214, 124, 115, 034, 007','content' => config('90DaysActionPlan.priority_16'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_17','condition' => 'IF ANY TWO (2) of the Energy Center (EM, INS, INT, or MOV) are GREATER THAN (>) 12 (1st Row)','content' => config('90DaysActionPlan.priority_17'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_18','condition' => 'IF ANY ONE (1) of the Energy Center (EM, INS, INT, or MOV) is GREATER THAN (>) 12 (1st Row)','content' => config('90DaysActionPlan.priority_18'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_19','condition' => 'IF ANY TWO (2) of the Energy Center (EM, INS, INT, or MOV) are LESS THAN (<) 7 (1st Row)','content' => config('90DaysActionPlan.priority_19'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_20','condition' => 'IF ANY ONE (1) of the Energy Center (EM, INS, INT, or MOV) is LESS THAN (<) 7 (1st Row)','content' => config('90DaysActionPlan.priority_20'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_21','condition' => 'IF the PV# = 0','content' => config('90DaysActionPlan.priority_21'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_22','condition' => 'IF the PV# < 0','content' => config('90DaysActionPlan.priority_22'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_23','condition' => 'IF the PV# > 12','content' => config('90DaysActionPlan.priority_23'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_24','condition' => 'IF the EP# < 25','content' => config('90DaysActionPlan.priority_24'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_25','condition' => 'IF the EP# > 35','content' => config('90DaysActionPlan.priority_25'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['priority' => 'priority_26','condition' => 'If ALL the above conditions are FALSE then use the following 90-Day Optimization Action Plan','content' => config('90DaysActionPlan.priority_26'),'type' => Admin::NINETY_DAYS_ACTION_PLAN,'updated_at' => Carbon::now()->format('Y-m-d H:i:s'), 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],

        ];

        DB::table('optimization_plan')->insert($plan);
    }
}
